---
# This is the TorqueBox configuration file. Refer to the TorqueBox
# documentation at http://torquebox.org/documentation/current/ 
# for all configuration options.
web:
  context: "/"
ruby:
  version: 1.9
jobs:
  messages.refresh:
    description: refresh message
    job: RefreshMessage
    cron: '*/15 * * * * ?'
web:
  session-timeout: 2 h